insert into users(name) values ('One');
insert into roles(name, roles_id) values ('Role1', 1);
insert into roles(name, roles_id) values ('Role2', 1);
insert into roles(name, roles_id) values ('Role3', 1);
insert into rules(rules_text) values ('Rule1');
insert into rules(rules_text) values ('Rule2');
insert into rules(rules_text) values ('Rule3');
insert into roles_rules(roles_id, rules_id) values (1, 1);
insert into roles_rules(roles_id, rules_id) values (1, 2);
insert into roles_rules(roles_id, rules_id) values (2, 2);
insert into roles_rules(roles_id, rules_id) values (2, 3);
insert into roles_rules(roles_id, rules_id) values (3, 1);
insert into roles_rules(roles_id, rules_id) values (3, 2);
insert into items(name, items_id) values ('Item', 1);
insert into comments(comments_text, items_id) values ('Comment1', 1);
insert into comments(comments_text, items_id) values ('Comment2', 1);
insert into comments(comments_text, items_id) values ('Comment3', 1);
insert into attachs(attachs_text, items_id) values ('Attach1', 1);
insert into attachs(attachs_text, items_id) values ('Attach2', 1);
insert into attachs(attachs_text, items_id) values ('Attach3', 1);
insert into categories(name, items_id) values ('Category1', 1);
insert into categories(name, items_id) values ('Category2', 1);
insert into categories(name, items_id) values ('Category3', 1);
insert into states(name, items_id) values ('State1', 1);
insert into states(name, items_id) values ('State2', 1);
insert into states(name, items_id) values ('State3', 1);